#  ## COLORED PHYREXIAN MANA ##
# MANA_COST_MAPPING = {
#     '{W}': 'ms ms-w',
#     '{U}': 'ms ms-u',
#     '{B}': 'ms ms-b',
#     '{R}': 'ms ms-r',
#     '{G}': 'ms ms-g',
#     '{T}': 'ms ms-tap',
#     '{Q}': 'ms ms-untap',
#     '{E}': 'ms ms-e',
#     '{X}': 'ms ms-x',
#     '{Y}': 'ms ms-y',
#     '{Z}': 'ms ms-z',
#     '{0}': 'ms ms-0',
#     '{1}': 'ms ms-1',
#     '{2}': 'ms ms-2',
#     '{3}': 'ms ms-3',
#     '{4}': 'ms ms-4',
#     '{5}': 'ms ms-5',
#     '{6}': 'ms ms-6',
#     '{7}': 'ms ms-7',
#     '{8}': 'ms ms-8',
#     '{9}': 'ms ms-9',
#     '{10}': 'ms ms-10',
#     '{11}': 'ms ms-11',
#     '{12}': 'ms ms-12',
#     '{13}': 'ms ms-13',
#     '{14}': 'ms ms-14',
#     '{15}': 'ms ms-15',
#     '{16}': 'ms ms-16',
#     '{17}': 'ms ms-17',
#     '{18}': 'ms ms-18',
#     '{19}': 'ms ms-19',
#     '{20}': 'ms ms-20',
#     '{100}': 'ms ms-100',
#     '{1000000}': 'ms ms-1000000',
#     '{W/U}': 'ms ms-wu ms-cost bw',
#     '{W/B}': 'ms ms-wb ms-cost bw',
#     '{B/R}': 'ms ms-br ms-cost bw',
#     '{B/G}': 'ms ms-bg ms-cost bw',
#     '{U/B}': 'ms ms-ub ms-cost bw',
#     '{U/R}': 'ms ms-ur ms-cost bw',
#     '{R/G}': 'ms ms-rg ms-cost bw',
#     '{R/W}': 'ms ms-rw ms-cost bw',
#     '{G/W}': 'ms ms-gw ms-cost bw',
#     '{G/U}': 'ms ms-gu ms-cost bw',
#     '{W/P}': 'ms ms-wp ms-cost',
#     '{U/P}': 'ms ms-up ms-cost',
#     '{B/P}': 'ms ms-bp ms-cost',
#     '{R/P}': 'ms ms-rp ms-cost',
#     '{G/P}': 'ms ms-gp ms-cost',
#     '{2/W}': 'ms ms-2w ms-cost bw',    
#     '{2/U}': 'ms ms-2u ms-cost bw',
#     '{2/B}': 'ms ms-2b ms-cost bw',
#     '{2/R}': 'ms ms-2r ms-cost bw',
#     '{2/G}': 'ms ms-2g ms-cost bw',
#     '{B/G/P}': 'ms ms-bgp ms-cost',
#     '{B/R/P}': 'ms ms-brp ms-cost',
#     '{G/U/P}': 'ms ms-gup ms-cost',
#     '{G/W/P}': 'ms ms-gwp ms-cost',
#     '{R/G/P}': 'ms ms-rgp ms-cost',
#     '{R/W/P}': 'ms ms-rwp ms-cost',
#     '{U/B/P}': 'ms ms-ubp ms-cost',
#     '{U/R/P}': 'ms ms-urp ms-cost',
#     '{W/B/P}': 'ms ms-wbp ms-cost',
#     '{W/U/P}': 'ms ms-wup ms-cost',
#     '{HW}': 'ms ms-w ms-half',
#     '{HR}': 'ms ms-r ms-half',
#     '{S}': 'ms ms-s',
#     '{C}': 'ms ms-c'
# }

MANA_COST_MAPPING = {
    '{W}': 'ms ms-w',
    '{U}': 'ms ms-u',
    '{B}': 'ms ms-b',
    '{R}': 'ms ms-r',
    '{G}': 'ms ms-g',
    '{T}': 'ms ms-tap',
    '{Q}': 'ms ms-untap',
    '{E}': 'ms ms-e',
    '{X}': 'ms ms-x',
    '{Y}': 'ms ms-y',
    '{Z}': 'ms ms-z',
    '{0}': 'ms ms-0',
    '{1}': 'ms ms-1',
    '{2}': 'ms ms-2',
    '{3}': 'ms ms-3',
    '{4}': 'ms ms-4',
    '{5}': 'ms ms-5',
    '{6}': 'ms ms-6',
    '{7}': 'ms ms-7',
    '{8}': 'ms ms-8',
    '{9}': 'ms ms-9',
    '{10}': 'ms ms-10',
    '{11}': 'ms ms-11',
    '{12}': 'ms ms-12',
    '{13}': 'ms ms-13',
    '{14}': 'ms ms-14',
    '{15}': 'ms ms-15',
    '{16}': 'ms ms-16',
    '{17}': 'ms ms-17',
    '{18}': 'ms ms-18',
    '{19}': 'ms ms-19',
    '{20}': 'ms ms-20',
    '{100}': 'ms ms-100',
    '{1000000}': 'ms ms-1000000',
    '{W/U}': 'ms ms-wu ms-cost bw',
    '{W/B}': 'ms ms-wb ms-cost bw',
    '{B/R}': 'ms ms-br ms-cost bw',
    '{B/G}': 'ms ms-bg ms-cost bw',
    '{U/B}': 'ms ms-ub ms-cost bw',
    '{U/R}': 'ms ms-ur ms-cost bw',
    '{R/G}': 'ms ms-rg ms-cost bw',
    '{R/W}': 'ms ms-rw ms-cost bw',
    '{G/W}': 'ms ms-gw ms-cost bw',
    '{G/U}': 'ms ms-gu ms-cost bw',
    '{W/P}': 'ms ms-wp-simple',
    '{U/P}': 'ms ms-up-simple',
    '{B/P}': 'ms ms-bp-simple',
    '{R/P}': 'ms ms-rp-simple',
    '{G/P}': 'ms ms-gp-simple',
    '{2/W}': 'ms ms-2w ms-cost bw',    
    '{2/U}': 'ms ms-2u ms-cost bw',
    '{2/B}': 'ms ms-2b ms-cost bw',
    '{2/R}': 'ms ms-2r ms-cost bw',
    '{2/G}': 'ms ms-2g ms-cost bw',
    '{B/G/P}': 'ms ms-bgp-simple ms-cost bw',
    '{B/R/P}': 'ms ms-brp-simple ms-cost bw',
    '{G/U/P}': 'ms ms-gup-simple ms-cost bw',
    '{G/W/P}': 'ms ms-gwp-simple ms-cost bw',
    '{R/G/P}': 'ms ms-rgp-simple ms-cost bw',
    '{R/W/P}': 'ms ms-rwp-simple ms-cost bw',
    '{U/B/P}': 'ms ms-ubp-simple ms-cost bw',
    '{U/R/P}': 'ms ms-urp-simple ms-cost bw',
    '{W/B/P}': 'ms ms-wbp-simple ms-cost bw',
    '{W/U/P}': 'ms ms-wup-simple ms-cost bw',
    '{HW}': 'ms ms-w ms-half',
    '{HR}': 'ms ms-r ms-half',
    '{S}': 'ms ms-s',
    '{C}': 'ms ms-c'
}

PLANESWALKER_LOYALTY_MAPPING = {
    'commom_css': 'ms',
    'start_loyalty': 'ms-5x ms-loyalty-start',
    'up_loyalty': 'ms-loyalty-up',
    'down_loyalty': 'ms-loyalty-down',
    'loyalty_amount': 'ms-2x ms-loyalty-'
}

MODAL_ICONS_MAPPING = {
    'day': 'ms ms-dfc-day',
    'night': 'ms ms-dfc-night',
    'sparck': 'ms ms-dfc-spark',
    'ignite': 'ms ms-dfc-ignite',
    'enchantment': 'ms ms-dfc-enchantment',
    'land': 'ms ms-land',
    'moon': 'ms ms-dfc-moon',
    'emrakul': 'ms ms-dfc-emrakul',
    'modal_front': 'ms ms-dfc-modal-face',
    'modal_back': 'ms ms-dfc-modal-back',
    'lesson': 'ms ms-dfc-lesson'
}